@IsTest
public with sharing class ChildService_Test {
 
    @IsTest
    static void updateParentDescription(){
        
        // Account parent = new Account(Name='Parent');
        // Account child1 = new Account(Name='child1', Description='child1');
        // Account child2 = new Account(Name='child2', Description='child2');
        // insert new List<Account>{parent, child1, child2};

        // child1.ParentId = parent.Id;
        // child2.ParentId = parent.Id;
        // insert new List<Account>{child1, child2};






        // acc.Description = String.format('The Child ID: {0} \n Child Name: {1}   \n Oldest Child Contact : {2}  \n The Child Contact Account ID: {3} \n The Child Contact Birthdate: {4}',
        //        new List<Object>{
        //           child.Id,
        //           child.Name,
        //           Age,
        //           con.AccountId,
        //           Con.Birthdate.format()
                 
        //        });

        // Test.startTest();
        // System.runAs(contextuser){
            
        // }
        // Test.stopTest();
        
    }
}
